<?php

namespace Modules\Admin\Entities;

use Illuminate\Database\Eloquent\Model;
use Modules\Admin\core\Services\ProductESService;
use Modules\common\components\constants\ConstantDefine;
use Modules\common\components\elasticsearch\ElasticSearch;
use Modules\common\components\queue\RabbitMQ;

class Product extends Model
{
    protected $table = 'sanpham';
    public $timestamps = false;
    public $primaryKey = 'MaSP';
    protected $fillable = [
        'TenSP',
        'Gia',
        'Thumbnail',
        'ThongTin',
        'NoiDung',
        'TomTat',
        'LuotXem',
        'SoLuongTon',
        'deleteFlag',
        'MaLoaiSP',
        'MaThuongHieu'
    ];
//    public static function boot()
//    {
//        parent::boot(); // TODO: Change the autogenerated stub
//        self::created(function ($model){
//            //self::buildProduct($model->id);
//            $service = new ProductESService();
//            $service->store($model->id);
//        });
//    }
    public static function buildProduct(int $id)
    {
        $data =[
            'id'=>$id
        ];
        $builder = false;
        $exchange = ConstantDefine::EXCHANGE_BACKEND;
        $routing_key = ConstantDefine::KEY_BACKEND_REDIS_PRODUCT;
        $queue = new RabbitMQ;
        if ($queue->isConnected()){
            $builder = $queue->pub(serialize($data), $exchange, $routing_key, true);
        }
        $builder ? true : false;
    }
}
